// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8ovkdB981wJIedDP6oHQudvXIgSu35Q',
    appId: '1:496878803702:web:09bd6e4ca462c93c90ead7',
    messagingSenderId: '496878803702',
    projectId: 'freshtrack-8064a',
    authDomain: 'freshtrack-8064a.firebaseapp.com',
    databaseURL: 'https://freshtrack-8064a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freshtrack-8064a.appspot.com',
    measurementId: 'G-NX7RPGLWTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhBysUcUjZqkbCgbch6_eZA1ofg2HsMys',
    appId: '1:496878803702:android:2f74b004637d35b390ead7',
    messagingSenderId: '496878803702',
    projectId: 'freshtrack-8064a',
    databaseURL: 'https://freshtrack-8064a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freshtrack-8064a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuf8-pvBJfMUeQ6lQPFFDw66m2GugSUAc',
    appId: '1:496878803702:ios:d6730af428cbb9af90ead7',
    messagingSenderId: '496878803702',
    projectId: 'freshtrack-8064a',
    databaseURL: 'https://freshtrack-8064a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freshtrack-8064a.appspot.com',
    iosBundleId: 'com.example.freshTrack3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuf8-pvBJfMUeQ6lQPFFDw66m2GugSUAc',
    appId: '1:496878803702:ios:25ec292d63af554590ead7',
    messagingSenderId: '496878803702',
    projectId: 'freshtrack-8064a',
    databaseURL: 'https://freshtrack-8064a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freshtrack-8064a.appspot.com',
    iosBundleId: 'com.example.freshTrack3.RunnerTests',
  );
}
